set(_CATKIN_CURRENT_PACKAGE "registration_viewer")
set(registration_viewer_MAINTAINER "Thiemo Wiedemeyer <wiedemeyer@informatik.uni-bremen.de>")
set(registration_viewer_DEPRECATED "")
set(registration_viewer_VERSION "0.0.1")
set(registration_viewer_BUILD_DEPENDS "roscpp" "rostime" "std_msgs" "sensor_msgs" "message_filters" "cv_bridge" "image_transport" "compressed_image_transport" "compressed_depth_image_transport" "kinect2_bridge" "libpcl-all-dev" "cv_bridge")
set(registration_viewer_RUN_DEPENDS "message_runtime" "roscpp" "rostime" "std_msgs" "sensor_msgs" "message_filters" "cv_bridge" "image_transport" "compressed_image_transport" "compressed_depth_image_transport" "libpcl-all-dev" "libpcl-all")
set(registration_viewer_BUILDTOOL_DEPENDS "catkin")